### ISSUE TITLE
Can't change name of "BLE Device"

### ISSUE THREAD

**Issue by gcarmix** [gl-inet/gl-ble-sdk#5]
Hi,
I can't find any way to change the BLE Device name of the router, it is stuck on "BLE Device" and I haven't found any clues in your code.
Changing the device name is mandatory to use it in any project other that an "Hello World" example

**Comment by gl-chenxiaosheng** [comment]
Hi,

You can try the new release version of master, it surpport to config gatt dynamically.
See https://github.com/gl-inet/gl-ble-sdk/tree/master/src/example/bletool#set_gattdb
https://github.com/gl-inet/gl-ble-sdk/blob/8938fac1753f2ac693b18ba3513c0ebf18f81a1d/src/lib/include/gl_bleapi.h#L462-L472
If have other questions, let me know.

**Comment by HeFeng1947** [comment]
Close outdated issues.
